using UnityEngine;

public class Terrain_1_Modifier : MonoBehaviour
{
    // Script Description:
    // - This script modifies the terrain generated by the PerlinNoiseTerrainGenerator.
    // - It applies modifications to the terrain height based on specified minimum and maximum height values.
    // - The script adds a value between minHeight and maxHeight to gradually increase the terrain height along the x-axis.
    [Header(
        "<b><size=13><color=#FFE066>Terrain Modifier Script</color></size></b>\n" +
        "<i><color=#FFF2B2>This script modifies the terrain generated by the PerlinNoiseTerrainGenerator.</color></i>\n" +
        "<i><color=#FFF2B2> - It applies modifications to the terrain height based on specified minimum and maximum height values.</color></i>\n" +
        "<i><color=#FFF2B2> - The script adds a value between minHeight and maxHeight to gradually increase the terrain height along the x-axis.</color></i>"
    )]
    
    // References
    [Header("<b><color=#FF9AA2><size=12>References</size></color></b>")]
    [SerializeField] private Terrain terrain; // Reference to the Terrain component
    [SerializeField] private TerrainTexturePainter terrainTexturePainter;
    
    // Terrain Modifier Settings
    [Header("<b><color=#FFB677><size=12>Terrain Modifier Settings</size></color></b>")]
    [SerializeField] private bool applyModification = true; // Whether to apply the height modification
    [SerializeField] private float minHeight = 0f; // Minimum height to apply modification
    [SerializeField] private float maxHeight = 10f; // Maximum height to apply modification
    
    
    public void OnTerrainGenerated()
    {
        if (!applyModification)
        {
            Debug.Log("Terrain modification is disabled.");
            return;
        }
        
        // Verify height values
        VerifyHeightValues(terrain.terrainData);
        
        TerrainData terrainData = terrain.terrainData;
        float xRange = terrainData.size.x;
        float[,] heights = terrainData.GetHeights(0, 0, (int)xRange, (int)terrainData.size.z);
        
        var heightModifierUnit = (maxHeight - minHeight) / xRange; // Calculate the height modifier per unit x
        
        // Gardually increase the terrain height along the x-axis
        for (int x = 0; x < heights.GetLength(0); x++)
        {
            var targetHeight = minHeight + (x * heightModifierUnit);
            var terrainHeightRange = terrainData.size.y;
            var targetHeightNormalized = targetHeight / terrainHeightRange;
            
            for (int z = 0; z < heights.GetLength(1); z++)
            {
                if (heights[x, z] < targetHeightNormalized)
                {
                    //heights[x, z] = targetHeightNormalized;
                    heights[x, z] = (heights[x, z] + targetHeightNormalized) / 2; // Average the current height with the target height
                }
            }
        }
        // Apply the modified heights back to the terrain
        terrainData.SetHeights(0, 0, heights);
        
        // Paint the terrain textures based on the modified heights
        terrainTexturePainter.PaintTerrain();
    }

    private void VerifyHeightValues(TerrainData terrainData)
    {
        if (minHeight < 0f)
        {
            Debug.LogWarning("Minimum height is less than 0. Setting to 0.");
            minHeight = 0f;
        }
        
        var terrainSize = terrainData.size;
        if (maxHeight > terrainSize.y)
        {
            Debug.LogWarning($"Maximum height {maxHeight} exceeds terrain size {terrainSize.y}. Setting to terrain size.");
            maxHeight = terrainSize.y;
        }
        
        if (minHeight > maxHeight)
        {
            Debug.LogWarning($"Minimum height {minHeight} is greater than maximum height {maxHeight}. Setting minimum height to maximum height.");
            minHeight = maxHeight;
        }
        
        Debug.Log($"Height values verified: Min Height = {minHeight}, Max Height = {maxHeight}");
        
    }
    
}
